### ISSUE TITLE
Built-in Bluetooth Failing to initialize.

### ISSUE THREAD

**Issue by chadodes** [darkxst/ha-operating-system#13]
Hello Folks.

### Error:
Bluetooth: Failed setup, will retry

**Setup:** 
    ->Hardware: iHost (AIBridge-26)
    ->MaskROM SD Install. (Ver 11.1.rc2)
    ->Full successful restore from existing arch64 HA device.

**Observations:**
Everything appears to be running wonderfully, noticed the notification about the newly discovered BT device.
Device shows up as hci0 with a HWA starting with 14:F5F9

**Steps taken to produce Error:**
    ->Click blue configure button from within "Discovered" section of integrations.

**Expected result:**
Device would configure normally and would become available to other add-ons.

**Steps taken to attempt to repair:**

- Reboot
- Remove traces of existing BT adaptor.
- Connected to console and traced supervisor logs

**Comment by darkxst** [comment]
Hi,
  Can you please provide logs both from supervisor, and journalctl logs from the host debug console.
  
  I have bluetooth running on my test system with an inkbird BT sensor. So I do wonder if its something that imported from your previous config

**Comment by chadodes** [comment]
> I have bluetooth running on my test system with an inkbird BT sensor. So I do wonder if its something that imported from your previous config

That's exactly what I thought.
Right now my journal is flooding with  "homeassistant kernel: Bluetooth: Controller acked invalid packet"

I am going to look and see if I can remove the bluetooth integration and re-add it.

**Comment by chadodes** [comment]
Does WLAN0 need to configured to further along any of the setup by chance? I added another USB BT adaptor and everything worked as it should.
The USB BT can be added, configured, and prompts for a location to be set.

I have included my Bluetooth Debug capture.
The HWA starting with 14:F5:F9 is the built in one.
The HWA starting with 5C:f3:70 is the USB (on an extension cable to prevent interference).
[BT_error_log.zip](https://github.com/darkxst/ha-operating-system/files/13469900/BT_error_log.zip)

Thanks!

Also, an interesting side note, using no external USB devices can get this thing down to a power consumption of 1.3 Watts.
Pretty amazing! Thank you for all of your hard work!
Adding a USB K-Datatraveler the device is still right around 2 watts or less.

**Comment by darkxst** [comment]
No wireless is not needed to be setup. Both Wireless and BT are on the same chip, but otherwise completely independent.

Any chance of getting the kernel side logs from journalctl when the setup fails? and also at boot time.

Yeh power consumption is super low, much better than a raspi.

> Thank you for all of your hard work!
Consider buying me a coffee if you would like to support this project ;) links on the main page.

**Comment by astangcong** [comment]
蓝牙好像不能用啊，一致报错
[2023-12-09T10-22-32.686Z.log](https://github.com/darkxst/ha-operating-system/files/13624084/2023-12-09T10-22-32.686Z.log)

**Comment by chadodes** [comment]
> 蓝牙好像不能用啊，一致报错
> 
> [2023-12-09T10-22-32.686Z.log](https://github.com/darkxst/ha-operating-system/files/13624084/2023-12-09T10-22-32.686Z.log)
> 
> 

感谢您提供日志文件。

**Comment by astangcong** [comment]
> > 蓝牙好像不能用啊，一致报错
> > [2023-12-09T10-22-32.686Z.log](https://github.com/darkxst/ha-operating-system/files/13624084/2023-12-09T10-22-32.686Z.log)
> 
> 感谢您提供日志文件。

我发现可能是偶发性的，有时候重启小概率可以恢复正常，不知道为什么

**Comment by darkxst** [comment]
Can you please post in English if possible!

I need to see the kernel logs either from debug console (via usb) or host ssh shell:
https://developers.home-assistant.io/docs/operating-system/debugging/

and run `journalctl -b0`

**Comment by astangcong** [comment]
> Can you please post in English if possible!
> 
> I need to see the kernel logs either from debug console (via usb) or host ssh shell: https://developers.home-assistant.io/docs/operating-system/debugging/
> 
> and run `journalctl -b0`

sorry，I do not know how to do it.
