### ISSUE TITLE
Images not loading in the Wiki

### ISSUE THREAD

**Issue by fabianoarruda** [darkxst/ha-operating-system#14]
If I'm not mistaken these images shows how to solder maskROM. However the images are not loading anymore. 

![images issue](https://github.com/darkxst/ha-operating-system/assets/5299669/5ac9a137-f3d4-40b8-bbbe-d1628d3b0808)

**Comment by darkxst** [comment]
Hi, 
  I wonder if this is a glitch in Github atm. The links are still good and show up when I go to edit the page. For now just open the links in a new page

**Comment by fabianoarruda** [comment]
@darkxst Already tried that, and didn't work. But then I tried accessing the page with an anonymous tab, and images loaded correctly. For some strange reason I don't have access to these images only when logged in with my GitHub account 🤷‍♂️

So it looks indeed like a Github glitch.

**Comment by darkxst** [comment]
yup somethings up, hopefully it resolves itself soon!
