### ISSUE TITLE
wlan0 not working 

### ISSUE THREAD

**Issue by chrismarine74** [darkxst/ha-operating-system#15]
i was successful install haos Hardware: iHost (AIBridge-26)  Operating System 11.1.rc2  in the emmc and    move data transfer to the sd, this from the first method ! all its perfect expt 
 I would like to highlight two things that I found, the first is that while  bluetooth works ok the wifi network does not work, only eth0 is visible in the system network. The second thing is when you run the reboot command, the system shuts down and you need to start it manually
thank you for the very good work on the project

**Comment by darkxst** [comment]
wifi seems a bit inconsistent, its working for some, but not others. I need to take another look at this.

Where abouts are you running `reboot` from? it seems to work here when run from the host shell, and also UI works here as well.

**Comment by freezingzz** [comment]
This is related to the configuration of the DTS file, you can contact the eWeLink team - they will tell you that you can change an IO level setting to make the WiFi module work more stable (They updated this part in the eWeLink CUBE V1.12 release). In addition, it is recommended to reduce the communication rate with the WiFi module to 10M instead of 25M

**Comment by darkxst** [comment]
they contacted me about a changed voltage level, but didnt provide any detail as to why!

**Comment by chrismarine74** [comment]
> Where abouts are you running `reboot` from? it seems to work here when run from the host shell, and also UI works here as well.

good morning, thanks for the support ,as for the reboot command, I run it  from the ui of the haos operating system
thanks regards

edit : finally I made a mistake, for the system reboot procedure, I had to wait , about 3-4 minutes for the process to complete

**Comment by darkxst** [comment]
can you try this build and see if wifi is working now?
https://github.com/darkxst/ha-operating-system/suites/18904841141/artifacts/1103966635

**Comment by chrismarine74** [comment]
unfortunately I try this build in attachment  but not solve the issue of wifi,
 thanks again for the support I appreciated

**Comment by darkxst** [comment]
I have one more possible fix to try, will push another image soon.

**Comment by darkxst** [comment]
Here is another build to try and fix wifi. Let me know if it helps!
https://github.com/darkxst/ha-operating-system/actions/runs/7295932096/artifacts/1130501332
