### ISSUE TITLE
Zigbee failure after Core 2023.12.1 update.

### ISSUE THREAD

**Issue by chadodes** [darkxst/ha-operating-system#16]
After updating to HA Core 2023.12.1 Zigbee ZHA fails to initialize. 

Restoring from backup to 2023.11.3 restores ZHA functionality. 

If I have some guidance on which log files you need for diagnostics and where they are, I can provide them.

**Comment by darkxst** [comment]
![image](https://github.com/darkxst/ha-operating-system/assets/993482/766a09c7-92d8-4b34-87fa-4198a9ce0700)

Try select the last flow control option?

**Comment by darkxst** [comment]
https://github.com/home-assistant/core/issues/105466

**Comment by chadodes** [comment]
> ![image](https://private-user-images.githubusercontent.com/993482/289337033-766a09c7-92d8-4b34-87fa-4198a9ce0700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjA4ODUsIm5iZiI6MTcwMjI2MDU4NSwicGF0aCI6Ii85OTM0ODIvMjg5MzM3MDMzLTc2NmEwOWM3LTkyZDgtNGIzNC04N2ZhLTQxOThhOWNlMDcwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwMjA5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTM1NzAwZGJlOTAzMDBlM2JhNGZlNTc2OWFlY2I3MGM2MTRmMWFjMzdiNzk4ZDNlMGY3NWQ2MGRkN2M3OWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hFHoPWZ1xcqrVHyE9OFo4Vy_cVakkeLL3LiYzLmP1jE)
> 
> Try select the last flow control option?

I can confirm deleting and re-creating the entry with the unlabeled radio option selected for flow control will resolve the issue.

**Comment by darkxst** [comment]
you dont need to delete ZHA, should be sufficient to just use "Migrate Radio" option to reconfigure

**Comment by VitorFrost** [comment]
I have disconnection since 2023.12.0 !

**Comment by darkxst** [comment]
@VitorFrost Have you reconfigured ZHA per the above flow control settings?

**Comment by VitorFrost** [comment]
this seems related: https://github.com/home-assistant/core/issues/105506

> @VitorFrost Have you reconfigured ZHA per the above flow control settings?

I am updating here to the latest core update, and will try it.

**Comment by VitorFrost** [comment]
So I went to ZHA in Devices & Services:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/16302178-d8f1-44a0-b41b-5c6d6e56f3f1)
Configure:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/a89c5412-40c7-4fd0-b9c5-d7f3d912dd9a)
Migrate Radio:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/86880623-1e2f-4127-be71-2206d72bf73c)
Submit:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/2f5e76c9-9d12-43e5-b1f5-2de3905ae7c9)
Migrate to a new radio:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/2e388d63-a11c-4c11-a28c-6503c5bc5d2e)
Submit
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/5fa012da-3cf1-49d6-90f9-0e1181a719f9)

But if I select Reconfigure, I only have this options:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/51063297-790f-4ded-a1b5-a7fc7d440c9f)
manually
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/a62d86df-94b1-48b6-ac1c-9d5ed2344654)
EZSP
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/133bc101-5d7d-4ff2-8edd-a8fa0997b552)
But got failled to connect on the empty option:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/3be10f45-0f4c-45c0-9b24-d4998aa62a74)

**Comment by darkxst** [comment]
"Migrate to new radio" wont work when there is an error with existing coordinator.
Your second workflow should work though, that is exactly what I did.
Perhaps try delete ZHA integration and start fresh? (it should still keep connected devices as they are stored in nvmem on the dongle)

**Comment by VitorFrost** [comment]
Ok, I found the culprit for the blank option not working, I tried to fix it installing and running the multiprotocol add-on. after uninstalling it, I am prompted with this options:
![image](https://github.com/darkxst/ha-operating-system/assets/5491480/63334e97-57de-464a-a2e3-647b91826e94)

**Comment by darkxst** [comment]
Ok that is expected, Either of the first two options should work.
