### ISSUE TITLE
设备无法联网（外网），测试的时候内网能的地址都能ping通，但是ping外网就不行了

### ISSUE THREAD

**Issue by astangcong** [darkxst/ha-operating-system#17]
Core
2023.12.1
Supervisor
2023.11.6
Operating System
11.1.rc2
Frontend
20231208.2
我的系统是用SD装的，Maskrom已经短接。
你好我的问题不知道是什么原因导致的haos连接丢失，所有外网无法连接，我用ssh输入 ha network info
显示的是
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: false
interfaces:
- connected: true
  enabled: true
  interface: eth0
  ipv4:
    address:
    - 192.168.1.5/24
    gateway: 192.168.1.1
    method: auto
    nameservers:
    - 223.5.5.5
    - 223.6.6.6
    ready: true
  ipv6:
    address:
    - XXXX:XX:XX:XX::XXX/128
    - XXX:XX:XX:XXXX:XXXX:XXXX:XXXX:XXXX/64
    - fe80::XXXX:XXXX:XXXX:XXXX/64
    gateway: fe80::XXXX:XXXX:XXXX:XXXX
    method: auto
    nameservers: []
    ready: true
  mac: XX:XX:XX:XX:XXXX
  primary: true
  type: ethernet
  vlan: null
  wifi: null
- connected: false
  enabled: false
  interface: wlan0
  ipv4:
    address: []
    gateway: null
    method: disabled
    nameservers: []
    ready: false
  ipv6:
    address: []
    gateway: null
    method: disabled
    nameservers: []
    ready: false
  mac: XX:XX:XX:XX:XX:XX
  primary: false
  type: wireless
  vlan: null
  wifi: null
supervisor_internet: false
前两天还好好着了

**Comment by darkxst** [comment]
> * 192.168.1.5/24
>   gateway: 192.168.1.1
>   method: auto
>   nameservers:
> * 223.5.5.5
> * 223.6.6.6

Is the gateway address valid? ie is your router on 192.168.1.1?
You are using external nameservers, make sure you can connect to these as well.
`nslookup <domain.com>`
`ping <dns_ip>`

**Comment by astangcong** [comment]
Of course, the gateway address and dns address are valid，I have another haos working on PVE with the same address，and it's network is fine. when nslookup www.baidu.com, it returns "server can't find www.baidu.com: servvfall"

**Comment by darkxst** [comment]
I dont change anything network related compared to other HAOS. So it should work the same as your other device.

**Comment by astangcong** [comment]
所以我也不知道是什么原因，我也没改动别的地方，前几天还好好地，莫名其妙的就发现需要联网的集成都报错，后来试了试发现是设备根本连不到外网。下次系统更新是什么时候，已经不想重刷系统了

**Comment by darkxst** [comment]
can you ping the dns ip addresses? given that local network is working, perhaps its something with your router?
There will be an update in the next week, but it doesnt change anything related to ethernet.

**Comment by astangcong** [comment]
> can you ping the dns ip addresses? given that local network is working, perhaps its something with your router? There will be an update in the next week, but it doesnt change anything related to ethernet.

dns IPaddress  ‘223.5.5.5’没有办法ping通（没有返回任何信息），另一个装在pve里的ha就可以ping通。更新的话我看看会不会恢复，不知道是不是下载某些集成或者ADDONS的时候导致的问题，如果更新后还不行那就再重装系统试试

**Comment by astangcong** [comment]
没找到原因，重新刷了系统就没有这个问题了
