### ISSUE TITLE
System Freezes while starting  the HA  system

### ISSUE THREAD

**Issue by RRR3d** [darkxst/ha-operating-system#25]
This is the log file i get before it freezes , I have done each step 1by 1 multiple times , It stops while in the preparing mode.
any ideas on what is the problem ? , btw I have tried the last 2 versions which are released. Thanks in advance. 
![image](https://github.com/darkxst/ha-operating-system/assets/105751665/39290bb3-987b-4242-bda6-0a8fe219b248)
![image](https://github.com/darkxst/ha-operating-system/assets/105751665/2e386cc5-676a-4991-bf45-3f270b534c46)

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
INFO: Using udev information from host
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
INFO: Starting local supervisor watchdog...
[__main__] Initializing Supervisor setup
[supervisor.docker.network] Can't find Supervisor network, creating a new network
[supervisor.bootstrap] Seting up coresys for machine: tinker
[supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/armv7-hassio-supervisor with version 2023.12.0
[supervisor.docker.supervisor] Connecting Supervisor to hassio-network
[supervisor.resolution.evaluate] Starting system evaluation with state initialize
[supervisor.resolution.evaluate] System evaluation complete
[__main__] Setting up Supervisor
[supervisor.api] Starting API on 172.30.32.2
[supervisor.hardware.monitor] Started Supervisor hardware monitor
[supervisor.dbus.manager] Connected to system D-Bus.
[supervisor.dbus.agent] Load dbus interface io.hass.os
[supervisor.dbus.hostname] Load dbus interface org.freedesktop.hostname1
[supervisor.dbus.logind] Load dbus interface org.freedesktop.login1
[supervisor.dbus.network] Load dbus interface org.freedesktop.NetworkManager
[supervisor.dbus.rauc] Load dbus interface de.pengutronix.rauc
[supervisor.dbus.resolved] Load dbus interface org.freedesktop.resolve1
[supervisor.dbus.systemd] Load dbus interface org.freedesktop.systemd1
[supervisor.dbus.timedate] Load dbus interface org.freedesktop.timedate1
[supervisor.host.services] Updating service information
[supervisor.host.sound] Updating PulseAudio information
[supervisor.host.sound] Can't update PulseAudio data: Failed to connect to pulseaudio server
[supervisor.host.network] Updating local network information
[supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
[supervisor.docker.monitor] Started docker events monitor
[supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
[supervisor.docker.interface] Found ghcr.io/home-assistant/armv7-hassio-cli versions: []
[supervisor.docker.interface] Attaching to ghcr.io/home-assistant/armv7-hassio-cli with version 2023.11.0
[supervisor.plugins.cli] Starting CLI plugin
[supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/armv7-hassio-cli with version 2023.11.0 - 172.30.32.5
[supervisor.docker.interface] Found ghcr.io/home-assistant/armv7-hassio-dns versions: []
[supervisor.docker.interface] Attaching to ghcr.io/home-assistant/armv7-hassio-dns with version 2023.06.2
[supervisor.plugins.dns] Starting CoreDNS plugin
[supervisor.hardware.monitor] Detecting add hardware /dev/bus/usb/001/002 - None
[supervisor.hardware.monitor] Detecting add hardware /dev/sg0 - None
[supervisor.hardware.monitor] Detecting add hardware /dev/bsg/0:0:0:0 - None
[supervisor.hardware.monitor] Detecting add hardware /dev/sg1 - None
[supervisor.hardware.monitor] Detecting add hardware /dev/bsg/0:0:0:1 - None
[supervisor.hardware.monitor] Detecting add hardware /dev/sdb - /dev/disk/by-id/usb-1000_1320_ab9240017045-0:1
[supervisor.hardware.monitor] Detecting add hardware /dev/sda - /dev/disk/by-id/usb-1000_1320_ab9240017045-0:0
[supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/armv7-hassio-dns with version 2023.06.2 - 172.30.32.3
[supervisor.plugins.dns] Updated /etc/resolv.conf
[supervisor.docker.interface] Found ghcr.io/home-assistant/armv7-hassio-audio versions: []
[supervisor.docker.interface] Attaching to ghcr.io/home-assistant/armv7-hassio-audio with version 2023.12.0
[supervisor.plugins.audio] Starting Audio plugin
[supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/armv7-hassio-audio with version 2023.12.0 - 172.30.32.4
[supervisor.docker.interface] Found ghcr.io/home-assistant/armv7-hassio-observer versions: []
[supervisor.docker.interface] Attaching to ghcr.io/home-assistant/armv7-hassio-observer with version 2023.06.0
[supervisor.plugins.observer] Starting observer plugin
[supervisor.docker.observer] Starting Observer ghcr.io/home-assistant/armv7-hassio-observer with version 2023.06.0 - 172.30.32.6
[supervisor.docker.interface] Found ghcr.io/home-assistant/armv7-hassio-multicast versions: []
[supervisor.docker.interface] Attaching to ghcr.io/home-assistant/armv7-hassio-multicast with version 2023.06.2
[supervisor.plugins.multicast] Starting Multicast plugin
[supervisor.docker.multicast] Starting Multicast ghcr.io/home-assistant/armv7-hassio-multicast with version 2023.06.2 - Host
[supervisor.homeassistant.secrets] Loaded 0 Home Assistant secrets
[supervisor.docker.interface] No version found for ghcr.io/home-assistant/tinker-homeassistant
[supervisor.homeassistant.core] No Home Assistant Docker image ghcr.io/home-assistant/tinker-homeassistant found.
[supervisor.docker.interface] Attaching to ghcr.io/home-assistant/tinker-homeassistant with version landingpage
[supervisor.homeassistant.core] Using preinstalled landingpage
[supervisor.homeassistant.core] Starting HomeAssistant landingpage
[supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
[supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/tinker-homeassistant with version landingpage
[supervisor.os.manager] Detect Home Assistant Operating System 11.3.rc1 / BootSlot A
[supervisor.store.git] Cloning add-on https://github.com/hassio-addons/repository repository
[supervisor.store.git] Cloning add-on https://github.com/esphome/home-assistant-addon repository
[supervisor.store.git] Cloning add-on https://github.com/home-assistant/addons repository
[supervisor.store] Loading add-ons from store: 72 all - 72 new - 0 remove
[supervisor.addons.manager] Found 0 installed add-ons
[supervisor.backups.manager] Found 0 backup files
[supervisor.discovery] Loaded 0 messages
[supervisor.ingress] Loaded 0 ingress sessions
[supervisor.resolution.check] Starting system checks with state setup
[supervisor.resolution.check] System checks complete
[supervisor.resolution.evaluate] Starting system evaluation with state setup
[supervisor.resolution.evaluate] System evaluation complete
[supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - setup
[supervisor.resolution.evaluate] Starting system evaluation with state setup
[supervisor.resolution.evaluate] System evaluation complete
[__main__] Running Supervisor
[supervisor.os.manager] Rauc: A - marked slot kernel.0 as good
[supervisor.addons.manager] Phase 'initialize' starting 0 add-ons
[supervisor.addons.manager] Phase 'system' starting 0 add-ons
[supervisor.addons.manager] Phase 'services' starting 0 add-ons
[supervisor.core] Skipping start of Home Assistant
[supervisor.addons.manager] Phase 'application' starting 0 add-ons
[supervisor.misc.tasks] All core tasks are scheduled
[supervisor.core] Supervisor is up and running
[supervisor.homeassistant.core] Home Assistant setup
[supervisor.docker.interface] Updating image ghcr.io/home-assistant/tinker-homeassistant:landingpage to ghcr.io/home-assistant/tinker-homeassistant:2023.12.3
[supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/tinker-homeassistant with tag 2023.12.3.
[supervisor.host.info] Updating local host information
[supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
[supervisor.resolution.check] Starting system checks with state running
[supervisor.resolution.checks.base] Run check for docker_config/system
[supervisor.resolution.checks.base] Run check for pwned/addon
[supervisor.resolution.checks.base] Run check for trust/supervisor
[supervisor.resolution.checks.base] Run check for multiple_data_disks/system
[supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
[supervisor.resolution.checks.base] Run check for security/core
[supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
[supervisor.updater] Board 'ihost' not found in version file. No OS updates.
[supervisor.resolution.checks.base] Run check for no_current_backup/system
[supervisor.resolution.module] Create new suggestion create_full_backup - system / None
[supervisor.resolution.module] Create new issue no_current_backup - system / None
[supervisor.resolution.checks.base] Run check for free_space/system
[supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
[supervisor.resolution.check] System checks complete
[supervisor.resolution.evaluate] Starting system evaluation with state running
[supervisor.resolution.evaluate] System evaluation complete
[supervisor.resolution.fixup] Starting system autofix at state running
[supervisor.resolution.fixup] System autofix complete
[supervisor.host.services] Updating service information
[supervisor.host.network] Updating local network information
[supervisor.host.sound] Updating PulseAudio information
[supervisor.host.manager] Host information reload completed`

**Comment by darkxst** [comment]
The initial boot is quite slow. You may just need to wait a bit longer. At a minimum it will take 15-20mins but can take longer than this.

**Comment by RRR3d** [comment]
Thank you for your prompt response. Regrettably, I encountered a system crash and freeze while waiting. I suspect the issue might be related to the system itself.
![image](https://github.com/darkxst/ha-operating-system/assets/105751665/a6e55bbd-b71b-4d7f-9b09-bd586678201a)
Could you provide guidance on how to address this technical challenge?

Thank you,

**Comment by darkxst** [comment]
Did it crash during usb update? can you get any logs via the debug console (over the usb-c port)?

**Comment by clfberlin** [comment]
Ok, ich habe mehrere iHosts. Ich kann mal versuchen, das Problem zu reproduzieren. Es passiert also während des Einrichtungsvorgangs? Und das war welche Version?
