### ISSUE TITLE
设备不具备WiFi连接功能吗？

### ISSUE THREAD

**Issue by astangcong** [darkxst/ha-operating-system#26]
我怎么记得之前好像有用WiFi连接家庭网络的选项啊，现在怎么只有有线连接了，或者说是我没找到在哪里可以设置连接WiFi？

**Comment by clfberlin** [comment]
Astangcong is aksing, why there is only Ethernet and no working WiFi connection.

**Comment by darkxst** [comment]
I still havent got to the bottom of the Wifi issues, some people are still seeing the same issue even with 11.3rc1. I am chatting with eWelink guys to see if I can get any further info, apparently there was a driver update but that for the rockchip kernel and not mainline.

In the meanwhile most USB wifi sticks should work (11.3rc1 added many more drivers)

**Comment by astangcong** [comment]
我好像记得之前1[11.1.rc2]版本的时候好像有看到过在系统-网络里除了eth0之外还有WiFi网卡的，但是用USB更新后就没找到了。

**Comment by darkxst** [comment]
11.3 only reduced the bus speed for WiFi, it shouldnt have stopped wifi working (but it maybe slower).

**Comment by astangcong** [comment]
那我需要重新刷一下系统试试吗？

**Comment by darkxst** [comment]
no that probably wont help, you can wait for next update which I will try find further fixes for.

**Comment by astangcong** [comment]
那下次更新大概是什么时候

**Comment by darkxst** [comment]
I need to sync with 11.4rc1 for CIFS bug, will try include it then, next few days

**Comment by darkxst** [comment]
there is a new build here to try fix wifi
https://github.com/darkxst/ha-operating-system/actions/runs/7508657537

**Comment by astangcong** [comment]
> there is a new build here to try fix wifi https://github.com/darkxst/ha-operating-system/actions/runs/7508657537

是下载这个文件然后U盘更新是吧？
https://github.com/darkxst/ha-operating-system/actions/runs/7508657537/artifacts/1166720947

**Comment by darkxst** [comment]
yes can update, or just try a fresh install on a new SD card

**Comment by astangcong** [comment]
> there is a new build here to try fix wifi https://github.com/darkxst/ha-operating-system/actions/runs/7508657537

U盘更新还是不行，现在已经更新到11.3.dev1705103056版本，但重启依旧是没有WiFi适配器，在ha配置-系统-网络里还是只有eth0

**Comment by darkxst** [comment]
hmm I'm about of ideas to fix this wifi at this point then! Its hard to debug when I dont have a board with this issue!

**Comment by astangcong** [comment]
那需要我把设备寄给你们排查一下吗？

**Comment by clfberlin** [comment]
I also have two older models of the iHost, where Wifi hardware is declared as 'missing', even with ewelink OS. My newer model shows no problems.

**Comment by darkxst** [comment]
> Wifi hardware is declared as 'missing', even with ewelink OS

Hmm if it doesnt even work in eWelink OS, not sure there is much hope!

**Comment by astangcong** [comment]
我这个确实是早期内测时候的设备，不知道是不是这个原因

**Comment by clfberlin** [comment]
My older iHosts both don't show Wifi. My newer iHost has no problem. Therefore I think there might have been hardware issues with the older ones.

**Comment by astangcong** [comment]
那还有解决的可能性吗？这个设备使用着确实比较方便，现在我是临时用的网线连接，但如果WiFi不能用的话我就不能把它放在想要放得位置（那里没有网线），确实是可惜了

**Comment by clfberlin** [comment]
With the newer model I have nor problem with Wifi. Maybe you could ask Sonoff? It might be a production failure. Otherwise maybe a USB-WiFi dongle will help? I have an iHost that also had a failure of the ethernet port and I used a USB-Ethernet dongle that worked.

**Comment by darkxst** [comment]
> Maybe you could ask Sonoff?

@astangcong Sonoff may replace it under warranty. I had one replaced for dead wifi chip (that failed about after 1 month of use!)

**Comment by astangcong** [comment]
一方面我去问问易微联，另一方面咱们这边是准备放弃这个问题的修复了吗，还有，如果第三方usb网卡都支持哪些，我手头一个好多年前的usb网卡插上去也不显示

**Comment by darkxst** [comment]
11.3 should support most USB Wifi sticks, however really old ones may not be supported. Mostly anything based on Mediatek or Realtek chips should work though avoid the older RTL8812AU chipset if your buying new. I am using a tp-link t3u nano on my odrioid HAOS and works well.

Unfortunately it can be a little hard to workout what actual chips are in products though!

**Comment by chrismarine74** [comment]
the problem with the wifi seems to exist in the first production models, I don't know if it's a hardware problem or a driver support issue, but now you ask the following question, I have installed haos in the emmc internal memory, how can I restore the original operating system ewelink  this to be returned for replacement under warranty if its hardware issue

**Comment by darkxst** [comment]
@chrismarine74 Just contact iTead, they have been pretty good with warranty and dont seem to mind having install community haos builds.

**Comment by astangcong** [comment]
> I need to sync with 11.4rc1 for CIFS bug, will try include it then, next few days

我看还一直没有更新新的版本呀，另外把系统安装到emmc的话只能从11.1rc2安装然后再通过升级包升级吗，为什么11.3没有找到boot.rc.img.xz这个文件

**Comment by darkxst** [comment]
I will skip 11.4 as were not impacted by CIFS bug. next release will be 11.5 and I will make a boot.img for that one. But generally you can just use the update files to upgrade as well.

**Comment by astangcong** [comment]
实际上我又买了个4G版本的新的ihost，准备刷系统试试有没有WIFI

**Comment by darkxst** [comment]
Install 11.2 check if wifi is working, then upgrade to 11.3 with rauc file and check again. Let me know the results!

**Comment by astangcong** [comment]
我在新买的4g版本上直接安装的11.3版本（安装在sd卡），目前WIFI是正常的。

**Comment by darkxst** [comment]
Wifi is working?

**Comment by astangcong** [comment]
是的，WIFI功能正常。目前我是同时连接有线和WIFI（人在外面没办法拔网线），手动禁用以后WIFI也是正常的。只是有一点，禁用有线的ipv4/ipv6以后重启机器会自动打开，别的一切正常。

**Comment by darkxst** [comment]
You may be able to disable wired via Network Manager profiles:
/etc/NetworkManager/system-connections/

**Comment by astangcong** [comment]
好的，等回去试试

**Comment by astangcong** [comment]
好像还有问题，只连接wifi的话内部的插件无法连接外网，和我在nas里建立的nodered也不能进行通信。
1.我连接usb看了一下，如果只连接wifi的话，看network info 里host_Internet：false，supervisor_Internet：false。但是如果插上网线和wifi同时连接以后network info 里host_Internet：true，supervisor_Internet：false（重启有时候也会是true）。这时候需要联网的插件就可以联网了。
2.但是，有线无线同时连接的话，两个IP中一个ip填入nodered里会导致ha无法和外部的nodered通信，ip改为另一个就可以了。

**Comment by astangcong** [comment]
我现在用了几天，但是不知道为什么，WIFI连接总是会自己断网，只能断电重启才能恢复

**Comment by astangcong** [comment]
不行啊，完全不能用wifi，一天掉线好机会，还不会自动重连，设备看着也是开机状态，就是不连接wifi，只能断电重启。现在根本用不成

**Comment by darkxst** [comment]
I've not had any issues with wifi disconnecting on my test ihost 2G that is running over wifi. However it also doesnt have ethernet connected so dont know if its related to that?

**Comment by astangcong** [comment]
大概什么时候会出新版本更新，看会不会有改善，这一天断网一次还得手动断电重启真的很麻烦

**Comment by darkxst** [comment]
I will update to sync with 12.0 soon, this has a newer kernel version so may help with your issues

**Comment by darkxst** [comment]
new release is up now

**Comment by astangcong** [comment]
更新完就看不到wlan0了

**Comment by tl-sl** [comment]
hmm it should work, but let me check something was missed when moving to new 6.6 kernel

**Comment by astangcong** [comment]
> hmm it should work, but let me check something was missed when moving to new 6.6 kernel

wifi问题还没解决吗，我现在发现偶尔eh0也会存在失效，必须重启才可以解决。

**Comment by darkxst** [comment]
You can try this build for wifi
https://github.com/darkxst/ha-operating-system/actions/runs/8171354230

**Comment by astangcong** [comment]
你们这太让人失望了，一个联网的问题都多久了还没解决，而且用作智能家居最大的要求也是最基本的就是稳定，现在三天两头出问题，和当时宣传的简直是天差地别

**Comment by darkxst** [comment]
did wifi work on that build? what problems are you having every 3 days?

**Comment by astangcong** [comment]
我已经没有时间精力再陪你们去这么来回测试了，不用这个烂设备了

**Comment by darkxst** [comment]
Closing this then.
