### ISSUE TITLE
update from usb

### ISSUE THREAD

**Issue by riddik14** [darkxst/ha-operating-system#27]
from ssh terminal

➜  ~ systemctl restart hassos-config
zsh: command not found: systemctl

from usb debug install update not start

Am I doing something wrong?

**Comment by astangcong** [comment]
你应该用usb连接电脑和ihost，然后打开putty，选择comX端口连接ihost以后再输入这条命令。直接在homeassistant的ssh里输入命令是不行的

**Comment by riddik14** [comment]
ok
