### ISSUE TITLE
USB to Serial Chip inside iHost

### ISSUE THREAD

**Issue by saschalev** [darkxst/ha-operating-system#31]
Hey, 
does anyone know what Driver I need for the iHost to make debug over USB possible? 
(i am on Mac) 
I couldn't find information what USB to Serial chip is built into the iHost.

Thanks! 

best regards, 
Sascha

**Comment by darkxst** [comment]
There is no USB to Serial Chip.

The USB-C is setup as OTG and provides a login console using Linux Gadget CDC driver.

Otherwise there is an internal 3pin UART header that is the debug console, that shows uboot and early kernel message. You need to connect this with any USB-to-Serial adaptor.
