### ISSUE TITLE
ETH0 DISABLED

### ISSUE THREAD

**Issue by chrismarine74** [darkxst/ha-operating-system#32]
I have lost the physical interface with IHOST
this happens for no reason and the only connection i have is via usb

![εικόνα](https://github.com/darkxst/ha-operating-system/assets/114772416/2292511f-0649-4bfe-b2cc-f79f879094af)

**Comment by clfberlin** [comment]
On one of my iHosts eth0 died out of nothing during operations (running HAOS). I could not reactivate it, even with the stock OS. Opened a ticket. Had to send a description and some pictures. They replaced it. That was one of the very early ones. And it also seemed to have WiFi issues. The replacement works smoothly.

**Comment by fabianoarruda** [comment]
It just happened to me. Ethernet stopped working out of nowhere. just a few months of use :/

@clfberlin Did you mention to them you were using HAOS? I wonder if this could void the warranty.

**Comment by clfberlin** [comment]
@fabianoarruda - They didn't care about that. I mentioned that Ethernet was neither working with stock OS nor visible via nmcli. The latter suggests that it was not running the Sonoff environment. Also they asked me to send pictures of the PCB. So opening it is no problem either.

**Comment by freezingzz** [comment]
https://github.com/darkxst/ha-operating-system/issues/40

This incorrect voltage domain configuration can damage the IO ports of the RV1126（RV1109） during use, preventing them from outputting proper voltage or data waveforms. This hardware damage issue has been verified and confirmed on the faulty devices received. Rockchip's official response also indicates that such a misconfiguration carries the risk of causing this damage - as clearly warned in the official Datasheet, advising users to avoid incorrect voltage domain parameters to prevent irreversible hardware damage. Once the IO ports are damaged, they can no longer communicate normally with the external Ethernet chip, which results in the failure of your Ethernet functionality. Even if you switch back to the native system at this point, your hardware has already been damaged by running the system with the incorrect voltage configuration.

**Comment by asprenzel** [comment]
If one does not use the onboard Ethernet and instead uses a USB Ethernet adapter from the start, is there still a risk of the voltage issue breaking the onboard chip?
