### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by riddik14** [darkxst/ha-operating-system#35]
[  609.532785] rk_gmac-dwmac ffc40000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[  609.533708] rk_gmac-dwmac ffc40000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -19)

ihost 2gbRAM

**Comment by darkxst** [comment]
Hi,
  Can you get the full kernel logs? also what update caused this?
