### ISSUE TITLE
64Bit version

### ISSUE THREAD

**Issue by brooqs** [darkxst/ha-operating-system#44]
Hello,

First of all, thank you for your work. I installed the system from the sdcard as you suggested and it was working without any problems. I noticed a problem during the migration. I learned that my air conditioner integration needed a library that only has a 64bit version. As far as I can see, the current build is built as 32bit. Is there a possibility of seeing a 64bit version in the future?

Thanks.

**Comment by darkxst** [comment]
The SoC in ihost is only 32-bit, its not possible to create 64bit builds for this.

**Comment by brooqs** [comment]
Wow,
Thank you so much for your quick response.
This was a big disappointment for me when many projects are moving towards 64bit. It has nothing to do with the title but I want to ask before opening another issue. As you know, sdcards are not reliable storages. They will eventually fail. Of course, there is also the speed issue. Is it possible to back up the flash with DD and use it on the flash?

**Comment by darkxst** [comment]
You can install HAOS onto the eMMC flash, however at 8GB it is too small for a full system, so you still need to use a data disk either on SD card or USB drive (sd card is probably faster than USB).

**Comment by brooqs** [comment]
Yes, as you said, 8GB is too little space, so I decided to continue with the SD card. Thank you very much for your answers. Have a great day.
