### ISSUE TITLE
Move data disk

### ISSUE THREAD

**Issue by brooqs** [darkxst/ha-operating-system#45]
Hi there, I installed Home Assistant on internal flash because I couldn't get a stable setup with an SD card. After that, I restored my backup. It's running now, and I tried to use the "move data disk" option to transfer data to the SD card. When I did that, it said the device would reboot, and then all the lights on the device turned off. I can't monitor the process, so I don't know when it's going to finish. Has anyone else experienced this? Does the device reboot again afterward? I've been waiting for more than 15 minutes and I'm constantly pinging, but I'm not getting any response. By the way, my operating system is Linux.

**Comment by darkxst** [comment]
> I can't monitor the process

Connect to the debug console (Serial) over Type-C port. You can then check if there are any errors relating to SD card or partition type.

**Comment by brooqs** [comment]
Serial port makes sense, I'll try that again. Thank you for your answer.
