### ISSUE TITLE
CPU temperature

### ISSUE THREAD

**Issue by riddik14** [darkxst/ha-operating-system#5]
Hi but command

cat /sys/class/thermal/thermal_zone*/temp

Not work. alternatives?

**Comment by darkxst** [comment]
Thermal Sensors, along with dynamic frequency scaling and PVTM are not yet implemented for rv1126/rv1109 SoC's in the mainline kernel. It will require porting some driver code across from Rockchip kernel in addition to the usual devicetree nodes. 

I will look at adding these in a future release.

**Comment by riddik14** [comment]
Ok. then this issue could become a pull request?

**Comment by darkxst** [comment]
Yes sure, if you would like to work on this I will happily merge any pull requests.

Thermels should be fairly straight forward, you can find a similar patch series that was for [rv1108 thermal](https://patchwork.kernel.org/project/linux-arm-kernel/patch/1503570475-7850-2-git-send-email-rocky.hao@rock-chips.com/), that atleast will give you an idea of which parts need to be picked up from Rockchip kernel. Actual code will differ.

OPP is also straight forward, may not need any driver changes just devicetree nodes
PVTM I've not really looked at, but probably leave this for last!

**Comment by riddik14** [comment]
I thank you for your effort but I don't know how to fix the drivers or the kernel.

**Comment by fabianoarruda** [comment]
+1 for this, I think would be a nice feature to have 🙌
