### ISSUE TITLE
Red Light Flashing after a power on/reboot

### ISSUE THREAD

**Issue by VitorFrost** [darkxst/ha-operating-system#7]
The iHost doesn't change the LED status after the boot process. I know @darkxst is working on it, but I've found a temporary fix:
https://github.com/VitorFrost/ha-operating-system/wiki/Temporary-FIX:-Removing-the-red-flashing-LED-after-a-reboot

**Comment by darkxst** [comment]
Hi Vitor, 
  Nice one, that was quick, guess the red light was really bugging you!

**Comment by darkxst** [comment]
This can also be done from the [Advanced SSH addon](https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md), by entering the following init commands. You will also have access to the command when you login via ssh.

![image](https://github.com/darkxst/ha-operating-system/assets/993482/ea82f8a5-a9b4-4280-a7a1-65df74de5127)

**Comment by darkxst** [comment]
I have release initial version of custom integration.

https://github.com/darkxst/ihost_indicator

**Comment by darkxst** [comment]
Closing this at the custom indicator is released now.
